[15] Log opened at 2024-12-07 08:30:01.685475
[15] [Config] INFO: Control socket set up successfully: '@xdebug-ctrl.15'
[15] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[15] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[15] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[15] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[41] Log opened at 2024-12-07 08:30:04.156654
[41] [Config] INFO: Control socket set up successfully: '@xdebug-ctrl.41'
[41] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[41] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[41] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[41] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[41] Log closed at 2024-12-07 08:30:04.159802

[168] Log opened at 2024-12-07 08:30:17.179901
[168] [Config] INFO: Control socket set up successfully: '@xdebug-ctrl.168'
[168] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[168] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[168] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[168] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[168] Log closed at 2024-12-07 08:30:17.290872

[173] Log opened at 2024-12-07 08:30:17.414065
[173] [Config] INFO: Control socket set up successfully: '@xdebug-ctrl.173'
[173] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[173] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[173] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[173] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[173] Log closed at 2024-12-07 08:30:17.498777

[178] Log opened at 2024-12-07 08:30:17.673987
[178] [Config] INFO: Control socket set up successfully: '@xdebug-ctrl.178'
[178] [Step Debug] INFO: Connecting to configured address/port: host.docker.internal:9012.
[178] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', poll success, but error: Operation now in progress (29).
[178] [Step Debug] WARN: Creating socket for 'host.docker.internal:9012', connect: Network is unreachable.
[178] [Step Debug] ERR: Could not connect to debugging client. Tried: host.docker.internal:9012 (through xdebug.client_host/xdebug.client_port).
[178] Log closed at 2024-12-07 08:30:17.757449

[15] Log closed at 2024-12-07 08:30:17.797134

